### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by ajohnson-512** [svt/encore#11]
Hello,

Taking a look at the Encore documentation [here,](https://svt.github.io/encore-doc/)  an example of connecting to a remote or non standard Redis instance is made with the following:

spring:
&nbsp; jackson:
&nbsp; time-zone: Europe/Stockholm

profile:
&nbsp; location: url:http://YOURPROFILESERVERURL/encore/prod/master/profiles.yml

redis:
    &nbsp;subscription-connection-pool-size: 25
    &nbsp;connection-pool-size: 32
    &nbsp;connection-minimum-idle-size: 5
    &nbsp;uri: redis://YOURINSTANCE:6379
    &nbsp;db: 1
<br>
However, in my testing, I have found the Redis information in this example is ignored, and Encore continues to attempt to connect to the default localhost/127.0.0.1 defaults.

The source code test yml actually shows a working example with the Redis connection coming under the spring: definition: https://github.com/svt/encore/blob/c25749cf2efbf4613402039df5c64beb037d3c3f/src/test/resources/application-test-local.yml 

We followed this in our implementation, and we were able to connect directly to a remote instance bound to private IP space, and instead of utilizing the `uri` connector, `host|port` was required to successfully connect.

cat src/main/resources/application-local.yml

spring:
&nbsp; redis:
&nbsp;&nbsp;&nbsp; subscription-connection-pool-size: 25
&nbsp;&nbsp;&nbsp; connection-pool-size: 32
&nbsp;&nbsp;&nbsp; connection-minimum-idle-size: 5
&nbsp;&nbsp;&nbsp; host: redis.ip.space.here
&nbsp;&nbsp;&nbsp; port: port
&nbsp;&nbsp;&nbsp; db: 1

service:
&nbsp;name: encore-local

profile:
&nbsp;location: file:/home/tux/files/profiles.yml

I hope this helps, as updating the example documentation could help save setup times going forward. 

Also, do you have any tips or best practices for running Encore in the background? We have some ideas here, but would like to hear from you on this.

**Comment by janderssonse** [comment]
Thanks for pointing that out, that has changed a while ago, and I agree, it should be better documented with maybe a link to https://github.com/redisson/redisson/blob/master/redisson-spring-boot-starter/README.md
and the example could be pointing to one of the tests properties in the application instead, to get rid maintenance issues with obsolete example configs. I'm closing this, and created an issue in the docs here https://github.com/svt/encore-doc/issues/21 . 

Well, I'm not sure what you are after with that, do you mean on a local machine, or.. we run it in dedicated docker containers on k8s and just scale nodes. Anyway, If you want to chat with me, I'm on the slack video-dev sometimes https://video-dev.herokuapp.com/, just look me up.
