### ISSUE TITLE
how to add processing nodes ?

### ISSUE THREAD

**Issue by deedos** [svt/encore#12]
Hi, I could not find at the docs how to add encore "relay" nodes to descentralize processing. Is there a way to do it ?
thanks a lot

**Comment by janderssonse** [comment]
Hi, there are much improvements for more descriptions in the documentation, (additions are welcomed). . Basically, there is not much work - just startup Encore instances (nodes) and point them to you main Redis setup (sentinel?/single?cluster?)-setup and Redis will handle the queue distribution work from by making sure each encore instance/node that is free and requests job gets it - so just add encore instances/nodes as you wish to scale. It is briefly described under "Scaling, distribution and queues" in the https://svt.github.io/encore-doc/#concepts 

(Additional: Each encore instance/node can also by itself be fine tuned to how many jobs it will concurrently run on each instance/node with the[ concurrency settings ](https://svt.github.io/encore-doc/#application-properties), which default is set to max 3 (2 really, it is 0-indexed)). The default should be fine though so you should not net to change this.).
