### ISSUE TITLE
Use the sample document to execute docker-compose and an error message appears

### ISSUE THREAD

**Issue by jd7352** [svt/encore#16]
When I used the docker-compose example in the documentation, I encountered the following error message:

encore_1  | WARNING: An illegal reflective access operation has occurred
encore_1  | WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (jar:file:/app/encore.jar!/BOOT-INF/lib/spring-core-5.3.9.jar!/) to constructor java.net.URI()
encore_1  | WARNING: Please consider reporting this to the maintainers of org.springframework.util.ReflectionUtils
encore_1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
encore_1  | WARNING: All illegal access operations will be denied in a future release

When I execute the test in the subsequent swagger, an error message appears:

encore_1  | 2021-12-27 08:46:51.657  INFO 1 --- [nio-8080-exec-7] s.s.o.e.h.EncoreJobHandler               : Added job to queue
encore_1  | 2021-12-27 08:46:54.355  INFO 1 --- [   scheduling-1] s.s.o.e.s.p.JobPoller                    : Handling job c859b390-deed-4cf3-81f4-71e25c74015e
encore_1  | 2021-12-27 08:46:54.369  INFO 1 --- [   scheduling-1] s.s.o.e.s.p.JobPoller                    : Running job
encore_1  | 2021-12-27 08:46:55.720  INFO 1 --- [   scheduling-1] s.s.o.e.s.EncoreService                  : Start EncoreJob(id=c859b390-deed-4cf3-81f4-71e25c74015e, externalId=null, profile=program, outputFolder=/tmp/output, baseName=quicktest_, createdDate=2021-12-27T08:46:51.365008Z, progressCallbackUri=null, priority=0, message=null, progress=0, speed=null, startedDate=null, completedDate=null, debugOverlay=false, logContext={}, seekTo=null, duration=null, thumbnailTime=null, inputs=[AudioVideoInput(uri=/tmp/input/test.mp4, videoLabel=main, audioLabel=main, params={}, dar=null, useFirstAudioStreams=2, cropTo=null, padTo=null, videoFilters=[], audioFilters=[], analyzed=VideoFile(file=/tmp/input/test.mp4, fileSize=579602170, format=MPEG-4, overallBitrate=8770157, duration=528.704, videoStreams=[VideoStream(format=AVC, codec=h264, profile=Main, level=4.1, width=1920, height=1080, sampleAspectRatio=null, displayAspectRatio=null, pixelFormat=yuv420p, frameRate=30/1, duration=528.666667, bitrate=8444000, bitDepth=8, numFrames=15860, isInterlaced=false, transferCharacteristics=BT.709)], audioStreams=[AudioStream(format=AAC, codec=aac, duration=528.666667, channels=2, samplingRate=48000, bitrate=317375)]), videoStream=null, audioStream=null, probeInterlaced=true)])
encore_1  | 2021-12-27 08:46:58.550 ERROR 1 --- [   scheduling-1] s.s.o.e.s.EncoreService                  : Job execution failed: Connection refused (Connection refused)
encore_1  | 
encore_1  | java.net.ConnectException: Connection refused (Connection refused)

How can I solve the above problem?

**Comment by janderssonse** [comment]
Did you get it to work on your own? The first part is not relevant, however the connection refused part seems to imply something was blocking the docker connection to redis.

**Comment by jd7352** [comment]
> Did you get it to work on your own? The first part is not relevant, however the connection refused part seems to imply something was blocking the docker connection to redis.

Thank you very much for your reply! In later tests, I found that this error was caused by an access failure to profiles.yml in the example. This problem has been solved, but we still have other problems that have not been solved, so we have not yet experienced the power of Encore. I Will continue, and hope to get everyone's help when necessary!

**Comment by janderssonse** [comment]
Thanks, I'm closing this then. The documentation needs some updates also, we will see when there is time for that.
