### ISSUE TITLE
How to implement filters？

### ISSUE THREAD

**Issue by jd7352** [svt/encore#18]
This is a great project and I have successfully experienced its power. Now I want to implement watermark or logo while transcoding, how can I pass parameters such as overlay coordinates, logo's url through program.yml ? Please give pointers, thanks!

**Comment by jd7352** [comment]
I can successfully execute the following commands in the ~/ffmpeg_encore/ directory:
`ffmpeg -i input.mp4 -vf "movie=logo.jpg[logo];[0:v][logo]overlay" output.mp4`
`ffmpeg -i input.mp4 -filter_complex "movie=logo.png[logo];[0:v][logo]overlay" output.mp4`

But entering the configuration through program.yml always returns an error. The configuration file is as follows:
`name: program
description: my profile
scaling: bicubic
encodes:
  - type: X264Encode
    suffix: 2069
    twoPass: true
    height: 720
    filter_complex: "movie=logo.png[logo];[0:v][logo]overlay"
    params:
      ss: 00:00:00
      t: 00:00:10
      b:v: 2069k
      maxrate: 3104k
      bufsize: 4138k
      r: 25
      vsync: 1
      pix_fmt: yuv420p
      force_key_frames: expr:not(mod(n,96))
      profile:v: main
      level: 3.1
    x264-params:
      deblock: 0,0
      aq-mode: 1
      bframes: 6
      keyint: 192
      keyint_min: 96
      ref: 4
`

**Comment by grusell** [comment]
`filter_complex` is not valid in encore encoding profiles, the correct keyword is `filters`. Also because of how the filter chain is put together by encore, in this case you will need to use a `null` filter to save the video input. You will also need to include the full path to your logo. 
So In your profile, you could use something like 
```
    filters: ["null[my-filter-in];movie=/full/path/to/logo/logo.jpg[logo];[my-filter-in][logo]overlay"]
```
Also, instead of specifying the `ss` and `t` parameters in the profile you could set `seekTo` and `duration` on the job you post in.

**Comment by jd7352** [comment]
> `filter_complex` is not valid in encore encoding profiles, the correct keyword is `filters`. Also because of how the filter chain is put together by encore, in this case you will need to use a `null` filter to save the video input. You will also need to include the full path to your logo. So In your profile, you could use something like
> 
> ```
>     filters: ["null[my-filter-in];movie=/full/path/to/logo/logo.jpg[logo];[my-filter-in][logo]overlay"]
> ```
> 
> Also, instead of specifying the `ss` and `t` parameters in the profile you could set `seekTo` and `duration` on the job you post in.

**Comment by jd7352** [comment]
> > `filter_complex`在 encore 编码配置文件中无效，正确的关键字是`filters`. 此外，由于 encore 将过滤器链组合在一起的方式，在这种情况下，您将需要使用`null`过滤器来保存视频输入。您还需要包含徽标的完整路径。所以在你的个人资料中，你可以使用类似的东西
> > ```
> >     filters: ["null[my-filter-in];movie=/full/path/to/logo/logo.jpg[logo];[my-filter-in][logo]overlay"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 此外，您可以在配置文件和发布的工作中设置和参数，而`ss`不是指定参数。`t``seekTo``duration`

marvelous! Following your method got the results I was hoping for, thanks a lot!
In addition, the use of ss and t parameters in the configuration file is because I need to generate a 10-second video preview in a single transcoding task at the same time, my configuration should be correct (currently it works, I am in Simplified the configuration file behind when submitting an issue)?

**Comment by jd7352** [comment]
> `filter_complex` is not valid in encore encoding profiles, the correct keyword is `filters`. Also because of how the filter chain is put together by encore, in this case you will need to use a `null` filter to save the video input. You will also need to include the full path to your logo. So In your profile, you could use something like
> 
> ```
>     filters: ["null[my-filter-in];movie=/full/path/to/logo/logo.jpg[logo];[my-filter-in][logo]overlay"]
> ```
> 
> Also, instead of specifying the `ss` and `t` parameters in the profile you could set `seekTo` and `duration` on the job you post in.

marvelous! Following your method got the results I was hoping for, thanks a lot!
In addition, the use of ss and t parameters in the configuration file is because I need to generate a 10-second video preview in a single transcoding task at the same time, my configuration should be correct (currently it works, I am in Simplified the configuration file behind when submitting an issue)?

**Comment by grusell** [comment]
Glad to hear your problem is solved! 

Oh I see, with that use case it makes sense to use `ss` and `t` the parameters like that.
