### ISSUE TITLE
Encore fails to start if redis server is not configured to allow `CONFIG` command

### ISSUE THREAD

**Issue by grusell** [svt/encore#25]
**Describe the bug**
If using a redis server that does not allow the `CONFIG` command, encore fails to start. Many/some commercial managed redis service (azure redis cache, aws redis cache) does not allow the `CONFIG` command and therefore can not be used together with encore.

It seems pring data redis uses the `CONFIG` command to set the 'notify-keyspace-events' property.  In managed redis services, this can usually be configured  in some other way, so it would make sense if this behaviour of spring data redis could be disabled. 

I will provide a PR to fix this.

**To Reproduce**
1. Add `rename-command CONFIG ""` to the config of your redis server
2. Run encore
3. Encore will fail to start

**Expected behavior**
It should be possible to configure encore to run even if the `CONFIG` command is disabled. For correct funcionality this will probably requiring configuring `notify-keyspace-events` on the server through some other means.

**Comment by fhermansson** [comment]
Fixed in v0.2.6. Thank you Gustav.
