### ISSUE TITLE
encore-worker-0.2.5 running failure

### ISSUE THREAD

**Issue by jd7352** [svt/encore#28]
Request Help:
I ran the encore-web-0.2.5-boot.jar normally in severA and was able to handle the task successfully. After that, I configured the application to connect to the serverA redies in the serverB. encore-worker-0.2.5-boot.jar running, it always automatically quits the program, and no obvious error message was found in the system log. Is there a problem with my configuration? Who can 1 me an example of a application.yml file?

Here is my application and startup log:
application-test.yml
`spring:
  main:
    allow-bean-definition-overriding: true
  data: 
    redis: 
      host: 10.193.1.157
      port: 6379 

logging:
  level:
    se.svt: debug

encore-settings:
  concurrency: 3
  local-temporary-encode: false
  poll-initial-delay: 1s
  poll-delay: 1s
  shared-work-dir: /data/share
  
  encoding:
    default-channel-layouts:
      3: "3.0"
    audio-mix-presets:
      default:
        default-pan:
          stereo: FL=FL+0.707107*FC+0.707107*BL+0.707107*SL|FR=FR+0.707107*FC+0.707107*BR+0.707107*SR
        pan-mapping:
          mono:
            stereo: FL=0.707*FC|FR=0.707*FC
      de:
        fallback-to-auto: false
        default-pan:
          stereo: FL<FL+1.5*FC+0.707107*BL+0.707107*SL|FR<FR+1.5*FC+0.707107*BR+0.707107*SR
        pan-mapping:
          "[5.1]":
            "[5.1]": c0=c0|c1=c1|c2<1.5*c2|c3=c3|c4=c4|c5=c5
          "[5.1(side)]":
            "[5.1]": c0=c0|c1=c1|c2<1.5*c2|c3=c3|c4=c4|c5=c5

profile:
  location: https://xxx.xxx.xxx.xxx/profiles.yml`

Start Log
`{"@timestamp":"2024-05-30T16:43:47.767927826+08:00","@version":"1","message":"HV000001: Hibernate Validator 8.0.1.Final","logger_name":"org.hibernate.validator.internal.util.Version","thread_name":"background-preinit","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:47.841235279+08:00","@version":"1","message":"Starting EncoreWorkerApplicationKt v0.2.5 using Java 17.0.10 with PID 7633 (/encore_worker/encore-worker-0.2.5-boot.jar started by root in /encore_worker)","logger_name":"se.svt.oss.encore.EncoreWorkerApplicationKt","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:47.841835632+08:00","@version":"1","message":"Running with Spring Boot v3.1.3, Spring v6.0.11","logger_name":"se.svt.oss.encore.EncoreWorkerApplicationKt","thread_name":"main","level":"DEBUG","level_value":10000}
{"@timestamp":"2024-05-30T16:43:47.842523969+08:00","@version":"1","message":"The following 1 profile is active: \"test\"","logger_name":"se.svt.oss.encore.EncoreWorkerApplicationKt","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:48.629525637+08:00","@version":"1","message":"Multiple Spring Data modules found, entering strict repository configuration mode","logger_name":"org.springframework.data.repository.config.RepositoryConfigurationDelegate","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:48.630417449+08:00","@version":"1","message":"Bootstrapping Spring Data Redis repositories in DEFAULT mode.","logger_name":"org.springframework.data.repository.config.RepositoryConfigurationDelegate","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:48.98126161+08:00","@version":"1","message":"Finished Spring Data repository scanning in 335 ms. Found 1 Redis repository interfaces.","logger_name":"org.springframework.data.repository.config.RepositoryConfigurationDelegate","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:49.470326869+08:00","@version":"1","message":"BeanFactory id=692df1a8-dbd8-3c67-94be-83a058f7446e","logger_name":"org.springframework.cloud.context.scope.GenericScope","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:49.919248754+08:00","@version":"1","message":"Redisson 3.23.2","logger_name":"org.redisson.Version","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:50.09451454+08:00","@version":"1","message":"1 connections initialized for 10.193.1.157/10.193.1.157:6379","logger_name":"org.redisson.connection.pool.MasterPubSubConnectionPool","thread_name":"redisson-netty-2-4","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:50.199700907+08:00","@version":"1","message":"24 connections initialized for 10.193.1.157/10.193.1.157:6379","logger_name":"org.redisson.connection.pool.MasterConnectionPool","thread_name":"redisson-netty-2-19","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:52.193971021+08:00","@version":"1","message":"Cannot determine local hostname","logger_name":"org.springframework.cloud.commons.util.InetUtils","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:52.257618004+08:00","@version":"1","message":"Started EncoreWorkerApplicationKt in 5.519 seconds (process running for 6.081)","logger_name":"se.svt.oss.encore.EncoreWorkerApplicationKt","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:52.260089149+08:00","@version":"1","message":"Polling queue 0","logger_name":"se.svt.oss.encore.EncoreWorkerApplication","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2024-05-30T16:43:52.282373758+08:00","@version":"1","message":"Stopping","logger_name":"se.svt.oss.encore.EncoreWorkerApplication","thread_name":"main","level":"INFO","level_value":20000}`

**Comment by Lunkers** [comment]
Workers are meant to be used in a situation wherein you have some sort of auto-scaling based on job queues, such as KEDA. A worker starts and runs the first job it gets from the redis queue, then dies. If there are no jobs in the queue, the worker will shut down. 

You _always_ need an encore-web instance running to receive and queue jobs. If you do not use auto-scaling, encore workers will not suit your use case.

**Comment by jd7352** [comment]
I have understood their working mechanism and this is a great design. Thank you for your answer!
