### ISSUE TITLE
The issue of using the 'movflags: faststart' parameter in chunked based encoding

### ISSUE THREAD

**Issue by jd7352** [svt/encore#30]
When using the 'movflags: faststart' parameter in chunked based encoding, it was observed that the temporary files were partitioned to move the 'moov' data forward. However, when the partitioned files were combined and the final file was output, the 'moov' data was restored to its default location. Without using chunked basedencoding, there is no such issue.

**Comment by fhermansson** [comment]
Try adding 
```
joinSegmentParams:
    movflags: +faststart
```
at the top level of your profile.
Please let us know if it helps.

**Comment by jd7352** [comment]
After testing, the parameter was placed at the top level of the profile and achieved the desired result. Thank you very much for your help!
