### ISSUE TITLE
Convert issue

### ISSUE THREAD

**Issue by sresmor** [svt/encore#4]
Hello,

when we try to convert a file, we get an error message: "Error pars
![download](https://user-images.githubusercontent.com/91996755/136114727-847d83cf-d723-4d66-a590-d0f791f22e45.jpg)
ing Profil...`

could you please help us with this issue?
Thank you,

**Comment by Lunkers** [comment]
Hi!

It seems like Encore does not find the profile you specified, and tries to convert a 404 page to an encore job (and failing). Are you sure that the x264-animated profile you've specified is located correctly?

We do not provide any profiles with the repository as-is; you can build your own by following the examples in [our documentation](https://svt.github.io/encore-doc/#profiles)

**Comment by janderssonse** [comment]
And always, if you find any sections we  should improve in the documentation, please let us know.

**Comment by janderssonse** [comment]
With no further input from the user, we are closing this. Another question was also raised, and that answer ended up in the documentation faq.
