### ISSUE TITLE
New Profile Creation Help

### ISSUE THREAD

**Issue by sresmor** [svt/encore#5]
Hello,

could you please help us to create new (XDCAM) profile and how to use it?

Best,

**Comment by janderssonse** [comment]
While we can not to much specific support, i'll try to give you some guidance, I suggest that, you

 1) get a simple profile running from the documentation examples, see https://github.com/svt/encore/issues  . 
 2) Then, see if you can do what you want with ffmpeg locally (it will make it much easier).  
 3)  if you can create what you want with ffmpeg first, it should be doable to map that to an profile.  Let me know how it is going

**Comment by janderssonse** [comment]
Hello @sresmor I'm closing this issue soon, the answer will end up in the faq in the documentation. Did you get it to work as wished?

**Comment by janderssonse** [comment]
Closing this, as we didn't hear more from the user, and the suggestions have been added in the faq at the documentation [PR#19](https://github.com/svt/encore-doc/pull/19)
